### ISSUE TITLE
do not compile on Windows

### ISSUE THREAD

**Issue by siteswapjuggler** [danoli3/ofxTexturePacker#17]
Hello,

as far as I tried this does not comple on Windows because of Poco/RegularExpression and ofxXmlSettings. Is there a quick way to fix it ? and have you confirmation of this addon working on Linux (my destination platform is a RPi).

Sincerely

**Comment by siteswapjuggler** [comment]
Ok sorry for that I just needed to include ofxPoco and ofxXmlSettings as add-on. A quick note in the add-on description would have been nice ;)

**Comment by danoli3** [comment]
Fixed on master now with C++11 changes! The code was always there just in a comment I hope you saw :D !
